services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ezuml'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '55432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
